Web/Models/DocumentViewModel.cs
using Data;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Web.Models.DocumentsVM;
using X.PagedList;

namespace Web.Models
{
    public class DocumentViewModel
    {
        public Guid Id { get; set; }
        public string Path { get; set; }
        public string DocumentName { get; set; }
        public bool IsRefusedByAbroadVoters { get; set; }
        public bool IsRefusedByPoliticalParty { get; set; }
        public string FileName { get; set; }
        public DateTime Date { get; set; }
        public int? TypeId { get; set; }
        public int? LanguageId { get; set; }
        public string LanguageName { get; set; }
        public string SimpleName { get; set; }
        public int? DocumentTypeId { get; set; }
        public int CentralListId { get; set; }
        public string SeenByUserName { get;   set; }

        public bool IsSeen { get; set; } = false;
     
        public string  SeenByUserId { get; set; }
    }
    public class DocListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        //public virtual List<List> Lists { get; set; }
    }
    public class DocumentListViewModel
    {
        public List<SearchDocumentViewModel> SearchLists { get; set; }
        public List<DocumentViewModel> Documents { get; set; }
        public Guid RootId { get; set; }
        public int ProjectId { get; set; }
        public int SubProjectId { get; set; }
        public int SubProjectItemId { get; set; }
        public int SubprojectSubItemId { get; set; }

        public int PermitId { get; set; }
        public List<LanguageViewModel> Languages { get; internal set; }
        public int InvestmentCompanyId { get; internal set; }
        public int ShareholderId { get; internal set; }
        public string docName { get; set; }
    }

    public class AddUpdateDocumentViewModel
    {
        public Guid Id { get; set; }
        public string Path { get; set; }
        public string DocumentName { get; set; }
        public DateTime Date { get; set; }
        public int? TypeId { get; set; }
        public int? AccessId { get; set; }
        public int DocumentTypeId { get; set; }
        public IFormFile File { set; get; }
        public List<DocumentViewModel> Documents { get; set; }
        public Guid? RootId { get; set; }
        public Guid? PoliticalPartyId { get; set; }
        public int? LanguageId { get; set; }
        public int? ProjectId { get; set; }
        public int? SubProjectId { get; set; }
        public int? PermitId { get; set; }
        public int? InvestmentCompanyId { get; set; }
        public int? SubprojectSubItemId { get; set; }
        public int? ShareholderId { get; set; }

    }
    public class SearchDocumentViewModel
    {
        public Guid Id { get; set; }
        public string Path { get; set; }
        public string DocumentName { get; set; }
        public DateTime Date { get; set; }
        public Guid? RootId { get; set; }
    }

    public class ScrollDocumentViewModel
    {
        public Guid Id { get; set; }
        public string Path { get; set; }
        public string DocumentName { get; set; }
        public string FileName { get; set; }
        public DateTime Date { get; set; }
        public int? TypeId { get; set; }
        public int? LanguageId { get; set; }
        public string LanguageName { get; set; }

        public bool FileExists { get; set; }
        public LanguageViewModel Language { get; set; }

    }
    public class UploadFileForAnyTable
    {
        public List<UploadDataForFileViewModel> UploadDocuments { get; set; }
        public List<IFormFile> Files { get; set; }
    }

    public class UploadDataForFileViewModel
    {
        public int? DocumentTypeId { get; set; }
        public string PoliticalPartyId { get; set; }

    }
    public class ReturnMsgApiViewModel
    {
        public string RecordId { get; set; }
        public bool IsSucceed { get; set; }
    }
}

Web/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using Services.Documents;
using Services.Enum;
using Web.Models;
using X.PagedList;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;
using Services.Languages;
using Web.Providers;
using Web.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.Models.DocumentsVM;
using DocumentFormat.OpenXml.VariantTypes;
using MimeKit.Encodings;

namespace Web.Controllers
{
    //[Authorize(Roles = "Administrator, DataEntry, Shareholder, BankOfficer, CEO")]
    public class DocumentController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IDocumentService _DocumentService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILanguageService _languageService;

        private readonly Microsoft.Extensions.Configuration.IConfiguration configuration;
        private readonly string basicPath = "";
        private readonly string downloadDocuments = "";

        public DocumentController(IMapper mapper, IDocumentService DocumentService, Microsoft.Extensions.Configuration.IConfiguration configuration, ILanguageService languageService, IWebHostEnvironment webHostEnvironment)
        {
            _mapper = mapper;
            _DocumentService = DocumentService;
            _webHostEnvironment = webHostEnvironment;
            basicPath = Path.Combine(_webHostEnvironment.WebRootPath, "Documents");
            this.configuration = configuration;
            _languageService = languageService;
            downloadDocuments = Path.Combine(_webHostEnvironment.WebRootPath, "DownloadableDocs");
        }


        [HttpGet]
        [ClaimRequirement(Mode.CanView, ControllerEnum.Document)]
        public IActionResult Index(Guid RootId, int page = 1, string searchName = null, int DocumetTypeId = 0)
        {
            var pageSize = 10;
            var model = new DocumentListViewModel();
            //model.Type = _mapper.Map<List<ListViewModel>>(_listService.GetListsByListTypeId(ListTypeEnum.Type));
            model.Languages = _mapper.Map<List<LanguageViewModel>>(_languageService.GetAllActive());
            //model.IssuingAuthority = _mapper.Map<List<ListViewModel>>(_listService.GetListsByListTypeId(ListTypeEnum.IssuingAuthority));
            //model.Access = _mapper.Map<List<ListViewModel>>(_listService.GetListsByListTypeId(ListTypeEnum.Access));
            var dbDocs = _DocumentService.GetAllAsQuerable(searchName, RootId, DocumetTypeId).ToPagedList(page, pageSize);
            var result = _mapper.Map<List<DocumentViewModel>>(dbDocs);
            model.Documents = result;
            ViewBag.searchName = searchName;
            ViewBag.List = dbDocs;
            ViewBag.DocumetTypeId = DocumetTypeId;
            model.RootId = RootId;



            return View(model);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Download(string filename)
        {
            if (filename == null)
                return Content("filename not present");


            // Path.Combine(this.Environment.WebRootPath, "Uploads");
            var path = Path.Combine(basicPath, filename);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;

            return File(memory, GetContentType(path), Path.GetFileName(path));
        }
        [ValidateAntiForgeryToken]
        [ClaimRequirement(Mode.CanEit, ControllerEnum.Document)]
        public JsonResult AddUpdatedocument(AddUpdateDocumentViewModel model, IFormFile file)
        {
            if (file == null)
            {
                return Json(new { success = false });
            }
            model.DocumentName = file.FileName;
            var mappedList = _mapper.Map<Document>(model);
            //var rootID = "48353566-60e2-4c4c-b6e3-08d8ef892f11";// kjo duhet me ardh prej Root-it
            //mappedList.RootId = Guid.Parse(rootID);// "48353566 -60e2-4c4c-b6e3-08d8ef892f11";
            _DocumentService.Insert(mappedList);
            UploadDocumentWithCodeLang(file, mappedList.Id, LanguagesDictionary.GetCodeFromLanguageId()[(int)mappedList.LanguageId].ToString());
            return Json(new { success = true });

        }

        private void UploadDocument(IFormFile file, Guid Id)
        {
            var pathExtension = Path.GetExtension(file.FileName);

            var fileName = Id.ToString() + CurrentLanguage + pathExtension;
            var path = Path.Combine(basicPath, fileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                // file.CopyToAsync(stream);
                file.CopyTo(stream);
            }
        }



        [ValidateAntiForgeryToken]
        [ClaimRequirement(Mode.CanEit, ControllerEnum.Document)]
        public JsonResult Update(AddUpdateDocumentViewModel model)
        {
            try
            {
                var dbNodeMapped = _DocumentService.GetById(model.Id);
                var nodeTypeMapped = _mapper.Map(model, dbNodeMapped);
                _DocumentService.Update(nodeTypeMapped);
            }
            catch
            {
                return Json(new { success = false });
            }

            return Json(new { success = true });
        }

        [HttpPost]
        [ClaimRequirement(Mode.CanDelete, ControllerEnum.Document)]
        public JsonResult Delete(Guid Id)
        {
            try
            {
                var dbNodeMapped = _DocumentService.GetById(Id);

                _DocumentService.Delete(Id);


            }
            catch
            {
                return Json(new { success = false });
            }



            return Json(new { success = true });
        }


        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsx", "application/vnd.openxmlformatsofficedocument.spreadsheetml.sheet"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
        }


        [HttpGet]
        public ActionResult GetConfigurationValue4MaxFileLengthInMB()
        {
            const string sectionName = "MySettings", paramName = "MaxFileLengthInMB";
            var MaxFileLength = configuration[$"{sectionName}:{paramName}"];

            return Json(new { parameter = MaxFileLength });
        }
        [HttpGet]
        public ActionResult GetConfigurationValue4MaxFileLengthPoliticalPartyInMB()
        {
            const string sectionName = "MySettings", paramName = "MaxFileLengthPoliticalPartyInMB";
            var MaxFileLength = configuration[$"{sectionName}:{paramName}"];

            return Json(new { parameter = MaxFileLength });
        }
        [HttpGet]
        public ActionResult GetConfigurationValue4MaxFileLengthPollingCenterInMB()
        {
            const string sectionName = "MySettings", paramName = "MaxFileLengtPollingCenterInMB";
            var MaxFileLength = configuration[$"{sectionName}:{paramName}"];

            return Json(new { parameter = MaxFileLength });
        }
        [HttpGet]
        public ActionResult GetConfigurationValue4MaxFileLengthMaxFileLengtAbroadVoterInMB()
        {
            const string sectionName = "MySettings", paramName = "MaxFileLengtAbroadVoterInMB";
            var MaxFileLength = configuration[$"{sectionName}:{paramName}"];

            return Json(new { parameter = MaxFileLength });
        }
        [HttpGet]
        public ActionResult GetConfigurationValue4MaxFileLengthMaxFileLengtSpecialNeedsInMB()
        {
            const string sectionName = "MySettings", paramName = "MaxFileLengtSpecialNeedsInMB";
            var MaxFileLength = configuration[$"{sectionName}:{paramName}"];

            return Json(new { parameter = MaxFileLength });
        }

        public bool ValidateFileImage(IFormFile files)
        {
            if (files != null)
            {
                string fileName = files.FileName;
                var pathExtension = Path.GetExtension(fileName);
                if (files.Length > 0 || fileName != "")
                {
                    if (pathExtension.ToLower() == ".png" || pathExtension.ToLower() == ".jpg" || pathExtension.ToLower() == ".jpeg")
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
                else
                {
                    return false;
                }
            }
            else
            {
                return false;
            }
        }

        public IActionResult callAnyProcedure(string nameProcedure = "ReportPollingCenterChange")
        {
            var callProcedure = new ProcedureProvider(configuration);
            var model = new DynamicRowAndColumns();

Web/Views/Document/Index.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@model Web.Models.DocumentListViewModel
@{
    ViewData["Title"] = "DocumentList";
    string currentLanguage = ViewContext.RouteData.Values["lang"].ToString();
    var sharedRes = (Dictionary<string, string>)ViewData["Shared"];

    var isPActive = ViewBag.DocumetTypeId == 0 ? "active" : "nav-txtcol";
    var isSActive = ViewBag.DocumetTypeId == 38 ? "active" : "nav-txtcol";
    var filename = Model.Documents.Where(c => c.FileName.Contains("doc")).Select(c => c.FileName).FirstOrDefault();
}

<div class="container">
    <main role="main" class="">
        @await Component.InvokeAsync("_GetRootDetails", new { RootId = Model.RootId })
        <div class="forma-gold">
            <h4>@sharedRes.CheckKey("Documents")</h4>
            <div class="row mt-4 mb-3">
                <div class="col-12">
                    <form action="#" method="get" class="">
                        <div class="row">
                            <input type="hidden" name="RootId" value="@Model.RootId" />
                            <input type="hidden" name="DocumetTypeId" value="@ViewBag.DocumetTypeId" />
                            <div class="form-group col-lg-3">
                                <input type="text" name="searchName" class="form-control" placeholder="@sharedRes.CheckKey("Name")" value="@ViewBag.searchName" autocomplete="off" />
                            </div>
                            <div class="col-lg-6">
                                <button type="submit" class="btn btn-outline-primary" data-clear="false"><i class="fa fa-search" aria-hidden="true"></i> @sharedRes.CheckKey("Search")</button>
                            </div>
                            <div class="form-group col-lg-3 text-lg-right">
                                <a class=" btn btn-outline-primary" href="/@currentLanguage/Root/RootCard?RootId=@Model.RootId">
                                    <i class="fa fa-home">
                                    </i> @sharedRes.CheckKey("BackToLegalDoc")
                                </a>

                            </div>
                            <div class="form-group col-lg-12 text-lg-right">
                                @if (User.CanWrite(ControllerEnum.Document))
                                {
                                    <button class=" btn btn-outline-success" type="button" data-toggle="modal" data-target=".AddUpdatedocument" id="AddNewBtn">
                                        <i class="fa fa-plus"></i>  @sharedRes.CheckKey("Add")
                                    </button>
                                }

                            </div>
                        </div>
                    </form>
                </div>
                <div class="container">
                    <ul class="nav nav-tabs">
                        <li class="nav-item ">
                            <a class="nav-link @isPActive" href="/@currentLanguage/Document?RootId=@Model.RootId&DocumetTypeId=0&searchName=@ViewBag.searchName">
                                @sharedRes.CheckKey("PreparatoryDocuments")
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  @isSActive " href="/@currentLanguage/Document?RootId=@Model.RootId&DocumetTypeId=38&searchName=@ViewBag.searchName">
                                @sharedRes.CheckKey("SourceDocs")
                            </a>
                        </li>
                    </ul>
                    <br>
                </div>
            </div>
            @if (User.CanRead(ControllerEnum.Document))
            {
                <div class="col-12">
                    <div class="row">
                        <table class="table table-hover table-bordered">
                            <thead class="table-info">
                                <tr style="font-weight:600">
                                    <td>
                                        @sharedRes.CheckKey("Name")
                                    </td>
                                    <td>
                                        @sharedRes.CheckKey("Type")
                                    </td>
                                    <td>
                                        @sharedRes.CheckKey("Access")
                                    </td>
                                    <td>
                                        @sharedRes.CheckKey("IssuingAuthority")
                                    </td>
                                    <td class="text-center">
                                        @sharedRes.CheckKey("Date")
                                    </td>
                                    <td class="text-center">
                                        @sharedRes.CheckKey("Language")
                                    </td>
                                    <td>@sharedRes.CheckKey("Preview")</td>
                                    <td width="12%">
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Documents)
                                {
                                    <tr>
                                        <td>
                                            <a href="@Url.ActionLink("Download", "Document", new { filename = item.FileName })">
                                                @{
                                                    var docName = item.DocumentName.Substring(0, item.DocumentName.Length > 60 ? 60 : item.DocumentName.Length);
                                                }
                                                @docName
                                            </a>
                                        </td>
                                        @*<td>@(item.IssuingAuthority != null ? item.IssuingAuthority.ListTranslations.FirstOrDefault().Name : "")</td>*@
                                        <td>@item.Date.ToShortDateString()</td>
                                        <td>@item.LanguageName</td>
                                        <td style="text-align:center">
                                            <span class="previewFile" data-docname="@docName" data-filename="@item.FileName" data-filexe="@item.FileName.Split(".")[1]"><i class="fa fa-eye"></i></span>
                                        </td>
                                        <td>
                                            @if (User.CanDelete(ControllerEnum.Document))
                                            {
                                                <button id="DeleteDocument" class="btn btn-sm btn-outline-danger deletedocument"
                                                        data-formstr="/@currentLanguage/Document/Delete" data-detailid="@item.Id" data-toggle="modal">
                                                    <i class="fa fa-remove"> <span class="DeleteHoverText"></span></i>
                                                    @sharedRes.CheckKey("Delete")
                                                </button>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>


                </div>
                @Html.PagedListPager((IPagedList)ViewBag.List, page => Url.Action("Index", new { page, lang = currentLanguage }))
            }

        </div>
        @section scripts
        {
            <script src="~/js/Document.js" asp-append-version="true"></script>
        }

        <div class="modal fade AddUpdatedocument" id="AddUpdatedocument" tabindex="-1" aria-labelledby="AddUpdatedocument" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">@sharedRes.CheckKey("Add")</h5>
                        <button type="button" class="close close1" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="Documentform" class="form-horizontal" action="/@currentLanguage/Document/AddUpdatedocument" data-actionupdate="/@currentLanguage/Document/Update" method="post">
                            @Html.AntiForgeryToken()
                            <input type="hidden" id="Id" name="Id" value="0" />
                            <input type="hidden" id="RootId" name="RootId" value="@Model.RootId" />
                            <input type="hidden" id="listtransid" name="ListTransId" />
                            <div class="form-group col-lg-12" style="display:inline-flex">
                                <h6 class="searchFilterParagraph">@sharedRes.CheckKey("Name") </h6>
                                @*<input class="form-control form-control-borderless required" type="file" placeholder="Name" id="name" name="DocumentName" autocomplete="off">*@
                                <input type="file" class="form-control-file required" id="File" name="File">
                            </div>
                      
                            <div class="form-group col-lg-12" style="display:inline-flex">
                                <h6 class="searchFilterParagraph">@sharedRes.CheckKey("Language") </h6>
                                <select class="form-control form-control-borderless required" name="LanguageId" id="languageId">
                                    @foreach (var document in Model.Languages)
                                    {
                                        <option value="@document.Id">@document.Name</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group col-lg-12" style="display:inline-flex">
                                <h6 class="searchFilterParagraph2">@sharedRes.CheckKey("Date") </h6>
                                <input type="text" id="Date" name="Date" value="" class="form-control datepicker form-control-borderless required" autocomplete="off" />
                            </div>
                        </form>
                        <br />
                        <div class="form-group col-lg-12" style="display:inline-flex">
                            <span class="w-100 alert alert-danger" id="incomingDocMsg1" hidden></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        @if (User.CanWrite(ControllerEnum.Document))
                        {
                            <button type="button" class="btn btn-outline-success" data-loading-text="@sharedRes.CheckKey("Saving")" id="btnSubmitItem"><i class="fa fa-check"></i> @sharedRes.CheckKey("Save")</button>
                            <button type="button" class="btn btn-outline-danger close1" data-dismiss="modal"><i class="fa fa-times"></i> @sharedRes.CheckKey("Close")</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </main>
    <div>
        @*<iframe src='https://view.officeapps.live.com/op/embed.aspx?src=http%3A%2F%2Fieee802%2Eorg%3A80%2Fsecmail%2FdocIZSEwEqHFr%2Edoc' width='100%' height='100%' frameborder='0'>
                This is an embedded <a target='_blank' href='http://office.com'>Microsoft Office</a> document, powered by <a target='_blank' href='http://office.com/webapps'>Office Online</a>.
            </iframe>*@
        @*src='https://view.officeapps.live.com/op/embed.aspx?src=@Url.ActionLink("Download", "Document", new { filename = filename })'*@

        @*<iframe src='https://view.officeapps.live.com/op/embed.aspx?src=http://lawdata.online/hr/Document/Download?filename=@filename' width='100%' height='100%' frameborder='0'>
                This is an embedded <a target='_blank' href='http://office.com'>Microsoft Office</a> document, powered by <a target='_blank' href='http://office.com/webapps'>Office Online</a>.
            </iframe>*@
    </div>
    <div class="modal fade" id="FilePreview" tabindex="-1" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="docName"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="setIframe" style="height:500px">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-danger close1" data-dismiss="modal"><i class="fa fa-times"></i> @sharedRes.CheckKey("Close")</button>
                </div>
            </div>
        </div>
    </div>



</div>

Web/Views/Document/callAnyProcedure.cshtml
@model Web.Providers.DynamicRowAndColumns
@{
    ViewData["Title"] = "callAnyProcedure";
}


<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-responsive-sm">
            <thead>
                <tr>
                    @{
                        foreach (var cols in Model.Cols)
                        {
                            <th>@cols</th>
                        }
                    }
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Rows)
                {
                    <tr>
                        @foreach (var data in item)
                        {
                            <td>@data</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>